/*CETI COLOMOS                                        
TGO EN CONTROL AUTOMÁTICO E INSTRUMENTACIÓN         
PRACTICA 2.4 COMUNICACIÓN SERIAL                     
Martín Ricardo Del Río Grageda 15300067             
Lázaro Fabricio Torres Orozco 15300277          
06 DE MAYO DE 2019*/

//DECLARAMOS LAS DIRECTIVAS QUE VAMOS A USAR
#INCLUDE <16F886.H> 
#DEVICE ADC = 8
#USE DELAY(CLOCK=4000000)   
#INCLUDE <LCD1.C>                                              
#FUSES INTRC_IO,NOWDT,NOPUT,MCLR,NOPROTECT,NOCPD,NOBROWNOUT 
#FUSES NOIESO,NOFCMEN,NOLVP,NODEBUG,NOWRT,BORV21  
#BYTE TRISA = 0X85            
#BYTE PORTA = 0X05      
#BYTE TRISB = 0X86        
#BYTE PORTB = 0X06         
#BYTE TRISC = 0X87              
#BYTE PORTC = 0X07
#USE RS232(BAUD=9600, XMIT=PIN_C6, RCV=PIN_C7, BITS=8)

//DECLARACIÓN DE VARIABLES GLOBALES
INT CANAL = 0, POT;
FLOAT P0, P1, P2, P3, P4;

//INTERRUPCIÓN PARA OBTENER EL VALOR ENVIADO POR EL PIC 1
#INT_RDA
VOID RDA_ISR(){
      CANAL = GETC();
}

//PROGRAMA PRINCIPAL
VOID MAIN(){

   //DECLARACIÓN DE PUERTOS E INICIALIACIÓN DE FUNCIONES
   TRISA=0XFF;
   TRISB=0X00;
   TRISC=0B10000000;
   PORTC = 0X00;
   ENABLE_INTERRUPTS(GLOBAL);
   ENABLE_INTERRUPTS(INT_RDA);
   SETUP_ADC(ADC_CLOCK_INTERNAL);
   SETUP_ADC_PORTS(sAN0|sAN1|sAN2|sAN3|sAN4);
   LCD_INIT();
   
   LCD_GOTOXY(1,1);
   PRINTF(LCD_PUTC,"CETI             \nTGO CONTROL     ");
   delay_ms(500);
   LCD_GOTOXY(1,1);
   PRINTF(LCD_PUTC,"PRISCILA VAZQUEZ \nREG 15300287    ");
   delay_ms(500);
   LCD_GOTOXY(1,1);
   PRINTF(LCD_PUTC,"OSCAR LOPEZ      \nREG 15300262    ");
   delay_ms(500);
   LCD_GOTOXY(1,1);
   PRINTF(LCD_PUTC,"PRACTICA 2.4     \nCOM SERIAL      ");
   
   //LA LCD NO VA A CAMBIAR HASTA QUE EL MENÚ DEL PIC1 SE PRESIONE *
   WHILE(CANAL != 10){
   }

   WHILE(TRUE){
      //OBTENER E IMPRIMIR LOS VALORES DE LOS 5 POTENCIÓMETROS
      SET_ADC_CHANNEL(0);
      DELAY_MS(20);
      P0 = READ_ADC();
      SET_ADC_CHANNEL(1);
      DELAY_MS(20);
      P1 = READ_ADC();
      SET_ADC_CHANNEL(2);
      DELAY_MS(20);
      P2 = READ_ADC();
      SET_ADC_CHANNEL(3);
      DELAY_MS(20);
      P3 = READ_ADC();
      SET_ADC_CHANNEL(4);
      DELAY_MS(20);
      P4 = READ_ADC();
      LCD_GOTOXY(1,1);
      PRINTF(LCD_PUTC,"A%3.0F B%3.0F C%3.0F      \nD%3.0F E%3.0F    ",P0, P1, P2, P3, P4);
      
      //SI ES PRESIONADO EL BOTÓN SE ENVÍA EL VALOR DEL CANAL ESTABLECIDO EN EL PIC1
      IF(BIT_TEST(PORTA,7) == 1){
         WHILE(BIT_TEST(PORTA,7) == 1);
         SET_ADC_CHANNEL(CANAL);
         DELAY_MS(20);
         POT = READ_ADC();
         PUTC(POT);
      }
   }
}
